name: taiga_api
version: 0.0.3
homepage: https://github.com/walletek/taiga_api
description: library to access taiga api.
authors:
  - Hadrien Lejard <hadrien.lejard@gmail.com>
  - Antoine Guittet <antoine.epitech@gmail.com>

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  http: ">=0.11.3+5"
  coffee_http: ^0.2.1
